sudo: required
services:
- docker
env:
  - MINIKUBE_OPTS=--vm-driver=none
language: bash
before_install:
  - env
  - sudo apt-get update
  - sudo apt-get install -qq make git curl socat
script:
  - curl -L https://git.io/reactionetes | bash
