matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
      - docker
      env:
        - MINIKUBE_OPTS=--vm-driver=none
        - REACTIONETES_NAME=travis-build-test
        - REACTIONETES_REPO=reactioncommerce/reaction
        - REACTIONETES_TAG=latest
        - REPLICAS=2
        - MONGO_REPLICAS=5
# Possible os x support in the future
    #- os: osx
    #  osx_image: xcode7.2

language: bash

addons:
  apt:
    packages:
      - curl
      - socat
      - time

before_install:
# install nsenter which is required for port forwarding
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then .travis/ubuntu-compile-nsenter.sh && sudo cp .tmp/util-linux-2.30.2/nsenter /usr/bin; fi
# Possible os x support in the future
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi

script:
# /bin/sh points to dash on trusty, which can cause some of the tests to fail
  - ls -alh `which sh`
# switching to bash
  - echo "MINIKUBE_OPTS= $MINIKUBE_OPTS \
          REACTIONETES_NAME= $REACTIONETES_NAME \
          REACTIONETES_REPO= $REACTIONETES_REPO \
          REACTIONETES_TAG= $REACTIONETES_TAG \
          REPLICAS= $REPLICAS \
          MONGO_REPLICAS= $MONGO_REPLICAS "

  - /usr/bin/time -v make -e ci
