# Default values for reactionetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
mongoReplicaCount: 3
image:
  repository: reactioncommerce/reaction
  tag: v1.5.7
  pullPolicy: IfNotPresent
service:
  name: reactioncommerce
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    - reactioncommerce.local
  annotations:
    kubernetes.io/ingress.class: reactioncommerce
    kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

#reactionetes specific values
reactionetesClusterDomain: reaction.local

# reaction specific values
reactionEmail: 'admin@localhost'
reactionUser: 'admin'
reactionAuth: 'r3@cti0n'
# No 'https://' on this it will be added later
reactionHostname:  'reactioncommerce.example.com'
reactionRoot_url:  'http://reactioncommerce.example.com'
