version: 2

jobs:
  build:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
      MINIKUBE_OPTS: "--vm-driver=none"
      REACTIONCOMMERCE_NAME: "circleci-build-test"
      MONGO_RELEASE_NAME: "circleci-mongodb-test"
      REACTION_API_NAME: "grape-ape-api"
      REACTIONCOMMERCE_REPO: "reactioncommerce/reaction"
      REACTIONCOMMERCE_TAG: "latest"
      REPLICAS: 2
      MONGO_REPLICAS: 3
      MINIKUBE_MEMORY: 7777
      MINIKUBE_CPU: 4
      HOME: /opt/circleci
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - checkout

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - run: .circleci/install.sh

      - restore_cache:
          keys:
            - r8s-v2-{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - r8s-v2-{{ arch }}-{{ .Branch }}
            - r8s-v2

      - restore_cache:
          keys:
            - minikube-v1-{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - minikube-v1-{{ arch }}-{{ .Branch }}
            - minikube-v1

      - run: touch ~/.bashrc ~/.bash_profile ~/.zshrc ~/.profile
      - run: rm ~/.profile
      - run: /usr/bin/time -v make -e run_dotfiles
      - run: echo '# bashrc'; cat ~/.bashrc
      - run: echo '# zshrc'; cat ~/.zshrc
      - run: echo '# bash_profile'; cat ~/.bash_profile
      - run: echo '# profile'; cat ~/.profile
      - run: bash .ci/envtest.sh
      - run: /usr/bin/time -v make -e linuxreqs

      - save_cache:
          key: r8s-v2-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - /home/circleci/.r8s

      - run: /usr/bin/time -v make -e ci

      - save_cache:
          key: minikube-v1-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - /home/circleci/.minikube
