version: 2

jobs:
  build:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
      MINIKUBE_OPTS: "--vm-driver=none"
      REACTIONCOMMERCE_NAME: "circleci-build-test"
      MONGO_RELEASE_NAME: "circleci-mongodb-test"
      REACTION_API_NAME: "grape-ape-api"
      REACTIONCOMMERCE_REPO: "reactioncommerce/reaction"
      REACTIONCOMMERCE_TAG: "latest"
      REPLICAS: 2
      MONGO_REPLICAS: 3
      MINIKUBE_MEMORY: 7777
      MINIKUBE_CPU: 4
    steps:
      - checkout

      - run: .circleci/install.sh

      - restore_cache:
          keys:
            - nsenter-cache--{{ arch }}-{{ .Branch }}-{{ checksum "/usr/bin/nsenter" }}
            - nsenter-cache--{{ arch }}-{{ .Branch }}
            - nsenter-cache

      - run: .ci/ubuntu-compile-nsenter.sh && sudo cp .tmp/util-linux-2.30.2/nsenter /usr/bin/

      - save_cache:
          key: nsenter-cache--{{ arch }}-{{ .Branch }}-{{ checksum "/usr/bin/nsenter" }}
          paths:
            - /usr/bin/nsenter

      - restore_cache:
          keys:
            - linuxreqs-cache--{{ arch }}-{{ .Branch }}
            - linuxreqs-cache

      - run: /usr/bin/time -v make -e linuxreqs

      - save_cache:
          key: linuxreqs-cache--{{ arch }}-{{ .Branch }}
          paths:
            - /usr/local/bin/minikube
            - /usr/local/bin/kubectl
            - /usr/local/bin/helm

      - run: /usr/bin/time -v make -e ci
