version: 2

jobs:
  build:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
      MINIKUBE_OPTS: "--vm-driver=none"
      REACTIONCOMMERCE_NAME: "circleci-build-test"
      MONGO_RELEASE_NAME: "circleci-mongodb-test"
      REACTIONCOMMERCE_REPO: "reactioncommerce/reaction"
      REACTIONCOMMERCE_TAG: "latest"
      REPLICAS: 2
      MONGO_REPLICAS: 3
    steps:
      - checkout

      - run: .circleci/install.sh

      - run: /usr/bin/time -v make -e linuxreqs

      - run: /usr/bin/time -v make -e ci
