version: 2

jobs:
  build:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
      MINIKUBE_OPTS: "--vm-driver=none"
      REACTIONCOMMERCE_NAME: "circleci-build-test"
      MONGO_RELEASE_NAME: "circleci-mongodb-test"
      REACTION_API_NAME: "grape-ape-api"
      REACTIONCOMMERCE_REPO: "reactioncommerce/reaction"
      REACTIONCOMMERCE_TAG: "latest"
      REPLICAS: 2
      MONGO_REPLICAS: 3
      MINIKUBE_MEMORY: 7777
      MINIKUBE_CPU: 4
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - checkout

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - run: .circleci/install.sh

      - restore_cache:
          keys:
            - nsenter-v1-{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - nsenter-v1-{{ arch }}-{{ .Branch }}
            - nsenter-v1

      - run: make /usr/local/bin/nsenter

      - save_cache:
          key: nsenter-v1-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - /usr/local/bin/nsenter

      - restore_cache:
          keys:
            - linuxreqs-cache--{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - linuxreqs-cache--{{ arch }}-{{ .Branch }}
            - linuxreqs-cache

      - run: /usr/bin/time -v make -e linuxreqs

      - save_cache:
          key: linuxreqs-cache--{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - /usr/local/bin/minikube
            - /usr/local/bin/kubectl
            - /usr/local/bin/helm

      - run: /usr/bin/time -v make -e ci
