---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  serviceName: {{ .Release.Name }}-mongo
  replicas: {{ .Values.mongoReplicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
        role: mongo
        environment: {{ .Release.Name }}-mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:3.4
          command:
            - mongod
            - "--replSet"
            - {{ .Release.Name }}-rs
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: {{ .Release.Name }}-mongo-pv
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment={{ .Release.Name }}-mongo"
      volumes:
        - name: {{ .Release.Name }}-mongo-pv
          emptyDir: {}
