---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  serviceName: {{ .Release.Name }}-mongodb
  replicas: {{ .Values.mongoReplicaCount }}
  selector:
    matchLabels:
      app: {{ template "mongostateful.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "mongostateful.fullname" . }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - mongod
            - "--replSet"
            - "mongodb-rs"
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          volumeMounts:
            - name: {{ .Release.Name }}-mongodb-pv
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongodb,environment={{ .Release.Name }}-mongodb"
      volumes:
        - name: {{ .Release.Name }}-mongodb-pv
          emptyDir: {}
