apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  serviceName: {{ .Release.Name }}-mongo
  replicas: 3
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:3.4.1
        command:
        - mongod
        - --replSet
        - {{ .Release.Name }}-rs
        ports:
        - containerPort: 27017
          name: web
      # This container initializes the mongodb, then sleeps.
      - name: init-mongo
        image: mongo:3.4.1
        command:
        - bash
        - /config/init.sh
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-mongo-init
