apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-reaction-config
data:
  reaction.email: {{ .Values.reactionEmail }}
  reaction.user: {{ .Values.reactionUser }}
  reaction.auth: {{ .Values.reactionAuth }}
  reaction.root_url: {{ .Values.reactionRoot_url }}
  reaction.hostname: {{ .Values.reactionHostname }}
  reaction.mongo_url: mongodb://{{ .Values.mongodbReleaseName }}-mongodb-replicaset/{{ .Values.mongodbName }}?replicaSet={{ .Values.mongodbReplicaSet }},useMongoClient=true,connectWithNoPrimary=true
  reaction.mongo_url_with_primary: mongodb://{{ .Values.mongodbReleaseName }}-mongodb-replicaset/{{ .Values.mongodbName }}?replicaSet={{ .Values.mongodbReplicaSet }}
  reaction.mongo_oplog_url: mongodb://{{ .Values.mongodbReleaseName }}-mongodb-replicaset/{{ .Values.mongodbName }}-oplog?replicaSet={{ .Values.mongodbReplicaSet }}
